baseURL = "https://abc.com/"
languageCode = "en-us"
title = "My Home Page"

[params]
  ShowLogo = true
  Logo = "/images/logo.png"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blogs"
    url = "/blogs"
    weight = 2

  [[menu.main]]
    name = "Docs"
    url = "http://localhost:3000"
    weight = 3
    [menu.main.params]
      newTab = true

  [[menu.main]]
    name = "App"
    url = "http://localhost:3001"
    weight = 4
    [menu.main.params]
      newTab = true
