version: "3.9"

services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - .:/site
    working_dir: /site
    command: ["server", "--bind", "0.0.0.0", "--baseURL=http://localhost", "--appendPort=false", "--disableFastRender"]

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    working_dir: /app
    command: ["npm", "run", "start"]

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "dev"]
